import { Prize, UserProfile } from './types';

export const BASE_USER_PROFILE: UserProfile = {
    id: '1',
    user_id: 'demo-user',
    email: 'usuario@demo.com',
    name: 'Usuario Demo',
    role: 'end_user',
    level: 1,
    created_at: '2024-01-15T10:00:00Z',
    phone: '',
    location: '',
    bio: ''
};

export const PRIZES: Prize[] = [
    {
        id: "1",
        name: "Chaqueta Observauto Premium",
        description: "Chaqueta exclusiva de la marca patrocinadora con tecnología térmica",
        points: 1000,
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        stock: 5,
        category: "premium",
    },
    {
        id: "2",
        name: "Power Bank Observauto 20,000mAh",
        description: "Carga rápida, diseño compacto, perfecto para viajes",
        points: 500,
        image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400",
        stock: 15,
        category: "tech",
    },
    {
        id: "3",
        name: "Kit de Herramientas Automotriz",
        description: "Set profesional de 50 piezas para mantenimiento vehicular",
        points: 800,
        image: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=400",
        stock: 8,
        category: "tools",
    },
    {
        id: "4",
        name: "Audífonos Bluetooth Premium",
        description: "Cancelación de ruido activa, 30 horas de batería",
        points: 600,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
        stock: 12,
        category: "tech",
    },
    {
        id: "5",
        name: "Mochila Observauto Tech",
        description: "Mochila antirrobo con puerto USB y compartimento para laptop",
        points: 400,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        stock: 20,
        category: "accessories",
    },
    {
        id: "6",
        name: "Smartwatch Deportivo",
        description: "Monitor de ritmo cardíaco, GPS integrado, resistente al agua",
        points: 1200,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
        stock: 3,
        category: "premium",
    },
    {
        id: "7",
        name: "Termo Inteligente 500ml",
        description: "Mantiene temperatura 12h, pantalla LED, recargable USB",
        points: 300,
        image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        stock: 25,
        category: "accessories",
    },
    {
        id: "8",
        name: "Llavero Observauto Premium",
        description: "Llavero metálico de lujo con acabado cromado",
        points: 100,
        image: "https://images.unsplash.com/photo-1582719471137-c3967ffb1c42?w=400",
        stock: 50,
        category: "accessories",
    },
];
